"""
Django settings for CSP project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 判断是否为 PythonAnywhere 生产环境
IS_PRODUCTION = 'PYTHONANYWHERE_DOMAIN' in os.environ

# 安全密钥配置
if IS_PRODUCTION:
    # 生产环境：从环境变量获取密钥
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-for-production-only')
else:
    # 开发环境：使用固定密钥
    SECRET_KEY = "django-insecure-^tya%lyr^bq8$h3=d$ohk^fy_yz&3idfz66aky+mfff)f=@8q1"

# 调试模式配置
DEBUG = not IS_PRODUCTION

# 允许的主机配置
if IS_PRODUCTION:
    # 生产环境：只允许特定的域名
    ALLOWED_HOSTS = [
        'yourusername.pythonanywhere.com',  # 替换为你的 PythonAnywhere 用户名
        'localhost.pythonanywhere.com',
    ]
else:
    # 开发环境：允许所有主机
    ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "home",      # 首页
    "rsharing",  # 我的资源分享平台
    "upzy",      # 上传资源
    "flview",    # 分类浏览
    "self",      # 个人中心
    "about",     # 关于我们
    "register",  # 登录注册界面
    "help",      # 帮助
]

# 根据环境配置中间件
if IS_PRODUCTION:
    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",  # 生产环境添加 WhiteNoise
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]
else:
    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

ROOT_URLCONF = "CSP.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",  # 添加媒体文件处理器
            ],
        },
    },
]

WSGI_APPLICATION = "CSP.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# 静态文件根目录（生产环境收集静态文件到此目录）
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 静态文件目录（开发环境）
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# WhiteNoise 静态文件存储配置
if IS_PRODUCTION:
    # 生产环境：使用压缩和缓存版本的静态文件
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    # 开发环境：使用标准存储
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 确保媒体文件夹存在
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)

# 确保 staticfiles 文件夹存在（只在生产环境需要）
if IS_PRODUCTION and not os.path.exists(STATIC_ROOT):
    os.makedirs(STATIC_ROOT)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 指定自定义用户模型
AUTH_USER_MODEL = 'register.CustomUser'

# 登录重定向设置
LOGIN_REDIRECT_URL = '/'           # 登录成功后跳转到首页
LOGOUT_REDIRECT_URL = '/'          # 登出后跳转到首页
LOGIN_URL = '/register/'           # 登录页面URL

# 安全设置（生产环境增强）
if IS_PRODUCTION:
    # 强制 HTTPS
    SECURE_SSL_REDIRECT = True  # PythonAnywhere 会自动处理 HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # 安全头
    SECURE_HSTS_SECONDS = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 日志配置
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': os.path.join(BASE_DIR, 'django_errors.log'),
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': True,
            },
        },
    }
else:
    # 开发环境安全设置
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# WhiteNoise 压缩和缓存设置（仅生产环境）
if IS_PRODUCTION:
    WHITENOISE_MAX_AGE = 31536000  # 1年缓存
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_MANIFEST_STRICT = False
    WHITENOISE_ALLOW_ALL_ORIGINS = True

# 文件上传设置
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# 会话设置
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2周（秒）
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# 缓存设置（简单内存缓存，适合小型项目）
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# 自定义设置
CSP_CONFIG = {
    'SITE_NAME': 'CSP 校园资源分享平台',
    'SITE_DESCRIPTION': '连接校园，共享优质资源',
    'MAX_UPLOAD_SIZE': 50 * 1024 * 1024,  # 50MB
    'ALLOWED_FILE_TYPES': ['.pdf', '.doc', '.docx', '.ppt', '.pptx', '.zip', '.rar', '.exe', '.mp4', '.mp3', '.jpg', '.jpeg', '.png'],
}