# Generated by Django 5.2.7 on 2025-11-13 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(max_length=200, verbose_name="资源名称"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("文档资料", "文档资料"),
                            ("软件工具", "软件工具"),
                            ("学习教程", "学习教程"),
                            ("模板资源", "模板资源"),
                        ],
                        max_length=50,
                        verbose_name="资源分类",
                    ),
                ),
                (
                    "resource_file",
                    models.FileField(
                        upload_to="resources/%Y/%m/%d/", verbose_name="资源文件"
                    ),
                ),
                (
                    "resource_desc",
                    models.TextField(blank=True, null=True, verbose_name="资源描述"),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源",
                "verbose_name_plural": "资源",
                "ordering": ["-upload_time"],
            },
        ),
    ]
