# Generated by Django 5.2.7 on 2025-11-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="name",
            new_name="real_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="显示名称"
            ),
        ),
    ]
